# # Example 1
# # Create an image with EXPOSE instruction
# FROM nginx:alpine
# LABEL maintainer="ASK"
# EXPOSE 80


# Commands 
# docker build -t demo .
# docker image history demo
# docker image inspect demo


# Example 2----------------------------------------------------------
# Create an image with EXPOSE to tcp & udp instruction
FROM nginx:alpine
LABEL maintainer="ASK"
EXPOSE 80
EXPOSE 90/udp